package emct.frames.service_adjustments;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;

/**
 *
 * @author Catalin Glavan
 */
public class fuel extends javax.swing.JPanel {

    /**
     * Creates new form asdasd
     * @param set
     */
    public fuel() {
        initComponents();
       // super.setVisible(set);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fuel_pump = new javax.swing.JScrollPane();
        p7 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton33 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jLabel146 = new javax.swing.JLabel();
        jButton50 = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();

        fuel_pump.getVerticalScrollBar().setUnitIncrement(15);
        fuel_pump.getHorizontalScrollBar().setUnitIncrement(15);

        p7.setBackground(Color.LIGHT_GRAY);
        p7.setToolTipText("");

        jLabel121.setForeground(setColor2);
        jLabel121.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel121.setText("Fuel pump 2 ");

        jLabel122.setForeground(setColor2);
        jLabel122.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel122.setText("&");

        jButton33.setBackground(java.awt.Color.orange);
        jButton33.setText("FIG 7");
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setFocusable(false);

        jScrollPane14.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 & 4", "Battery voltage"}
            },
            new String [] {
                "Terminals", "Voltage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane14.setViewportView(jTable14);

        jLabel146.setForeground(setColor2);
        jLabel146.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel146.setText("Checking operation -");

        jButton50.setBackground(java.awt.Color.orange);
        jButton50.setText("FIG 15");
        jButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton50.setFocusable(false);

        jLabel124.setText("• Switch ignition ON. ");

        jLabel147.setText("• Fuel pump should run for approximately 1 second. ");

        jLabel148.setText("• If pump does not run:Switch ignition OFF. ");

        jLabel149.setText("• Remove fuel pump relay.");

        jLabel150.setText("• Connect battery voltage supply to relay base terminal 4 with switched lead");

        jLabel151.setText("• Fuel pump should run continuously when switch is operated.");

        jLabel152.setText("• If pump does not run:Switch ignition OFF.");

        jLabel153.setText("• Disconnect fuel pump multi-plug.");

        jButton51.setBackground(java.awt.Color.orange);
        jButton51.setText("FIG 15");
        jButton51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton51.setFocusable(false);

        jButton52.setBackground(java.awt.Color.orange);
        jButton52.setText("FIG 7");
        jButton52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton52.setFocusable(false);

        jLabel134.setText("• Switch ignition ON. ");

        jLabel135.setText("• Check for battery voltage between harness multi-plug terminals");

        jLabel156.setText("• If battery voltage is not indicated: Check wiring.");

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel121)
                            .addGroup(p7Layout.createSequentialGroup()
                                .addComponent(jLabel146)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel122)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton50)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14)
                            .addGroup(p7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel147)
                                    .addComponent(jLabel124)
                                    .addComponent(jLabel148)
                                    .addComponent(jLabel149)
                                    .addComponent(jLabel151)
                                    .addComponent(jLabel152)
                                    .addComponent(jLabel153)
                                    .addGroup(p7Layout.createSequentialGroup()
                                        .addComponent(jLabel150)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton52))
                                    .addComponent(jLabel134)
                                    .addGroup(p7Layout.createSequentialGroup()
                                        .addComponent(jLabel135)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton51))
                                    .addComponent(jLabel156))
                                .addGap(0, 310, Short.MAX_VALUE))))
                    .addGroup(p7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator8)))
                .addContainerGap())
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel121)
                .addGap(18, 18, 18)
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel122)
                    .addComponent(jButton33)
                    .addComponent(jLabel146)
                    .addComponent(jButton50))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel124)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel147)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel148)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel149)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel150)
                    .addComponent(jButton52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel151)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel152)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel153)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel134)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel135)
                    .addComponent(jButton51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel156)
                .addGap(26, 26, 26)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fuel_pump.setViewportView(p7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fuel_pump)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fuel_pump)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private final Color setColor = new Color(255, 204, 0);
    private final Color setColor2 = new Color(15, 89, 193);
    private final Color setColor3 = new Color(242, 227, 196);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane fuel_pump;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable14;
    private javax.swing.JPanel p7;
    // End of variables declaration//GEN-END:variables
}
