/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emct.en.frames.c_intake_system;

import emct.en.forms.default_images;
import java.awt.Point;

/**
 *
 * @author Catalin Glavan
 */
public class volume_air extends javax.swing.JPanel {

    /**
     * Creates new form injectors
     */
    public volume_air(Point setPoint) {
        this.point = setPoint;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fig19_1 = new javax.swing.JButton();
        jLabel91 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        fig19 = new javax.swing.JButton();
        fig18 = new javax.swing.JButton();
        jLabel86 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel92 = new javax.swing.JLabel();
        fig18_4 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        fig18_3 = new javax.swing.JButton();
        fig18_5 = new javax.swing.JButton();
        jLabel85 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel80 = new javax.swing.JLabel();
        fig18_6 = new javax.swing.JButton();
        jLabel104 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        fig18_1 = new javax.swing.JButton();
        jLabel108 = new javax.swing.JLabel();
        fig18_2 = new javax.swing.JButton();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jLabel109 = new javax.swing.JLabel();
        fig18_7 = new javax.swing.JButton();
        jLabel110 = new javax.swing.JLabel();
        fig19_2 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        fig18_9 = new javax.swing.JButton();
        fig19_3 = new javax.swing.JButton();
        jLabel112 = new javax.swing.JLabel();
        fig18_8 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(226, 224, 211));

        fig19_1.setBackground(java.awt.Color.orange);
        fig19_1.setText("FIG 19");
        fig19_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig19_1.setFocusable(false);
        fig19_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig19_1ActionPerformed(evt);
            }
        });

        jLabel91.setText("• Disconnect intake air trunking from VAF sensor");

        jLabel90.setText("• Ensure ignition switched OFF. ");

        jLabel100.setText("NOTE: Incorporates intake air temperature (IAT) sensor. ");

        jLabel101.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(15, 89, 193));
        jLabel101.setText("&");

        jLabel89.setText("• Clean off any gummy deposits with solvent. if necessary.");

        fig19.setBackground(java.awt.Color.orange);
        fig19.setText("FIG 19");
        fig19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig19.setFocusable(false);
        fig19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig19ActionPerformed(evt);
            }
        });

        fig18.setBackground(java.awt.Color.orange);
        fig18.setText("FIG 18");
        fig18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18.setFocusable(false);
        fig18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18ActionPerformed(evt);
            }
        });

        jLabel86.setText("• Disconnect intake air trunking from VAF sensor");

        jLabel98.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(15, 89, 193));
        jLabel98.setText("Checking earth connection - ");

        jLabel103.setText("• Disconnect VAF sensor multi-plug ");

        jLabel102.setText("• Ensure ignition switched OFF. ");

        jLabel92.setText("• Disconnect VAF sensor multi-plug");

        fig18_4.setBackground(java.awt.Color.orange);
        fig18_4.setText("FIG 18");
        fig18_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_4.setFocusable(false);
        fig18_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_4ActionPerformed(evt);
            }
        });

        jLabel88.setText("• Check for smooth operation. ");

        jLabel81.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(15, 89, 193));
        jLabel81.setText("Checking operation - ");

        jLabel93.setText("• Operate sensor flap over full extent of travel.");

        fig18_3.setBackground(java.awt.Color.orange);
        fig18_3.setText("FIG 18");
        fig18_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_3.setFocusable(false);
        fig18_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_3ActionPerformed(evt);
            }
        });

        fig18_5.setBackground(java.awt.Color.orange);
        fig18_5.setText("FIG 18");
        fig18_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_5.setFocusable(false);
        fig18_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_5ActionPerformed(evt);
            }
        });

        jLabel85.setText("• Ensure ignition switched OFF. ");

        jScrollPane9.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2 & 3", "Flap closed", "610 \u2126 approx."},
                {"2 & 4", "Flap closed", "60 \u2126 approx. "},
                {"2 & 3", "Flap fully open", "280 \u2126 approx. "},
                {"2 & 4", "Flap fully open", "780 \u2126 approx. "}
            },
            new String [] {
                "Terminals", "Condition", "Resistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane9.setViewportView(jTable9);

        jLabel80.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(15, 89, 193));
        jLabel80.setText("Volume air flow (VAF) sensor ");

        fig18_6.setBackground(java.awt.Color.orange);
        fig18_6.setText("FIG 18");
        fig18_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_6.setFocusable(false);
        fig18_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_6ActionPerformed(evt);
            }
        });

        jLabel104.setText("• Check resistance between harness multi-plug terminal and earth ");

        jLabel87.setText("• Operate sensor flap over full extent of travel. ");

        jLabel97.setText("• Check resistance between VAF sensor terminals .");

        fig18_1.setBackground(java.awt.Color.orange);
        fig18_1.setText("FIG 18");
        fig18_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_1.setFocusable(false);
        fig18_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_1ActionPerformed(evt);
            }
        });

        jLabel108.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(15, 89, 193));
        jLabel108.setText("Checking resistance - ");

        fig18_2.setBackground(java.awt.Color.orange);
        fig18_2.setText("FIG 18");
        fig18_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_2.setFocusable(false);
        fig18_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_2ActionPerformed(evt);
            }
        });

        jLabel99.setText("• Resistance change should be smooth.");

        jScrollPane10.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2 & 4", "Engine idling", "0, 9 V approx."},
                {"2 & 4", "2000 rpm", "1.5 V approx."},
                {"2 & 4", "4000 rpm", "2.2 V approx. "}
            },
            new String [] {
                "Terminals", "Condition", "Voltage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane10.setViewportView(jTable10);

        jLabel109.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(15, 89, 193));
        jLabel109.setText("Checking supply voltage -");

        fig18_7.setBackground(java.awt.Color.orange);
        fig18_7.setText("FIG 18");
        fig18_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_7.setFocusable(false);
        fig18_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_7ActionPerformed(evt);
            }
        });

        jLabel110.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(15, 89, 193));
        jLabel110.setText("&");

        fig19_2.setBackground(java.awt.Color.orange);
        fig19_2.setText("FIG 19");
        fig19_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig19_2.setFocusable(false);
        fig19_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig19_2ActionPerformed(evt);
            }
        });

        jScrollPane11.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"4 & earth", "Zero"}
            },
            new String [] {
                "Terminals", "Resistance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane11.setViewportView(jTable11);

        jLabel105.setText("• Ensure ignition switched OFF.");

        jLabel106.setText("• Disconnect VAF sensor multi-plug ");

        jLabel107.setText("• Switch ignition ON. ");

        jLabel111.setText("• Check voltage between harness multi-plug terminals ");

        fig18_9.setBackground(java.awt.Color.orange);
        fig18_9.setText("FIG 18");
        fig18_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_9.setFocusable(false);
        fig18_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_9ActionPerformed(evt);
            }
        });

        fig19_3.setBackground(java.awt.Color.orange);
        fig19_3.setText("FIG 19");
        fig19_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig19_3.setFocusable(false);
        fig19_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig19_3ActionPerformed(evt);
            }
        });

        jLabel112.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(15, 89, 193));
        jLabel112.setText("Checking signal -");

        fig18_8.setBackground(java.awt.Color.orange);
        fig18_8.setText("FIG 18");
        fig18_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fig18_8.setFocusable(false);
        fig18_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fig18_8ActionPerformed(evt);
            }
        });

        jScrollPane12.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3 & 4", "5 V approx."}
            },
            new String [] {
                "Terminals", "Voltage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane12.setViewportView(jTable12);

        jLabel113.setText("• Ensure ignition switched OFF.");

        jLabel114.setText("• Do not disconnect multi-plug.Acces s VAF sensor multi-plug terminals.");

        jLabel115.setText("• Check voltage between multi-plug terminals.");

        jLabel116.setText("• Start engine.");

        jLabel117.setText("• Increase rpm to specified values.");

        jLabel118.setText("• Allow to idle .");

        jLabel119.setText("• Check voltage between multi-plug terminals.");

        jLabel120.setText("• Voltage change should be smooth.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel85)
                                    .addComponent(jLabel87)
                                    .addComponent(jLabel89)
                                    .addComponent(jLabel88)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel86)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel81)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel108)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_2))
                                    .addComponent(jLabel100)
                                    .addComponent(jLabel80))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel90)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel92)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel91)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_4))
                                    .addComponent(jLabel97)
                                    .addComponent(jLabel93)
                                    .addComponent(jLabel99)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel98)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel101)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel103)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel104)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig19_1))
                                    .addComponent(jLabel102)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel109)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig18_7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel110)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fig19_2)))
                                .addGap(0, 431, Short.MAX_VALUE))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fig18_8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel106)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fig18_9))
                    .addComponent(jLabel105)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel111)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fig19_3))
                    .addComponent(jLabel107))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel120)
                    .addComponent(jLabel119)
                    .addComponent(jLabel117)
                    .addComponent(jLabel114)
                    .addComponent(jLabel113)
                    .addComponent(jLabel116)
                    .addComponent(jLabel118)
                    .addComponent(jLabel115))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel100)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(fig18))
                .addGap(18, 18, 18)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(fig18_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel89)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel108)
                    .addComponent(fig18_2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel91)
                    .addComponent(fig18_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel92)
                    .addComponent(fig18_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel99)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fig18_5)
                    .addComponent(jLabel101)
                    .addComponent(fig19)
                    .addComponent(jLabel98))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel103)
                    .addComponent(fig18_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel104)
                    .addComponent(fig19_1))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fig18_7)
                    .addComponent(jLabel110)
                    .addComponent(fig19_2)
                    .addComponent(jLabel109))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel105)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel106)
                    .addComponent(fig18_9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel107)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel111)
                    .addComponent(fig19_3))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fig18_8)
                    .addComponent(jLabel112))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel113)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel114)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel116)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel118)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel115)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel119)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fig18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18ActionPerformed
        if (evt.getSource() == fig18) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18ActionPerformed

    private void fig18_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_1ActionPerformed
        if (evt.getSource() == fig18_1) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_1ActionPerformed

    private void fig18_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_2ActionPerformed
        if (evt.getSource() == fig18_2) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_2ActionPerformed

    private void fig18_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_4ActionPerformed
        if (evt.getSource() == fig18_4) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_4ActionPerformed

    private void fig18_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_3ActionPerformed
        if (evt.getSource() == fig18_3) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_3ActionPerformed

    private void fig18_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_5ActionPerformed
        if (evt.getSource() == fig18_5) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_5ActionPerformed

    private void fig19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig19ActionPerformed
        if (evt.getSource() == fig19) {
            new default_images("FIG 19", "/emct/images/figures/fig19.jpg", point);
        }
    }//GEN-LAST:event_fig19ActionPerformed

    private void fig18_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_6ActionPerformed
        if (evt.getSource() == fig18_6) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_6ActionPerformed

    private void fig19_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig19_1ActionPerformed
        if (evt.getSource() == fig19_1) {
            new default_images("FIG 19", "/emct/images/figures/fig19.jpg", point);
        }
    }//GEN-LAST:event_fig19_1ActionPerformed

    private void fig18_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_7ActionPerformed
        if (evt.getSource() == fig18_7) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_7ActionPerformed

    private void fig19_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig19_2ActionPerformed
        if (evt.getSource() == fig19_2) {
            new default_images("FIG 19", "/emct/images/figures/fig19.jpg", point);
        }
    }//GEN-LAST:event_fig19_2ActionPerformed

    private void fig18_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_9ActionPerformed
        if (evt.getSource() == fig18_9) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_9ActionPerformed

    private void fig19_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig19_3ActionPerformed
        if (evt.getSource() == fig19_3) {
            new default_images("FIG 19", "/emct/images/figures/fig19.jpg", point);
        }
    }//GEN-LAST:event_fig19_3ActionPerformed

    private void fig18_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fig18_8ActionPerformed
        if (evt.getSource() == fig18_8) {
            new default_images("FIG 18", "/emct/images/figures/fig18.jpg", point);
        }
    }//GEN-LAST:event_fig18_8ActionPerformed

    private Point point;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fig18;
    private javax.swing.JButton fig18_1;
    private javax.swing.JButton fig18_2;
    private javax.swing.JButton fig18_3;
    private javax.swing.JButton fig18_4;
    private javax.swing.JButton fig18_5;
    private javax.swing.JButton fig18_6;
    private javax.swing.JButton fig18_7;
    private javax.swing.JButton fig18_8;
    private javax.swing.JButton fig18_9;
    private javax.swing.JButton fig19;
    private javax.swing.JButton fig19_1;
    private javax.swing.JButton fig19_2;
    private javax.swing.JButton fig19_3;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables
}
