/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emct.frames;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Catalin Glavan
 */
public class emct extends javax.swing.JFrame implements language {

    /**
     * Creates new form emct
     */
    public emct() {
        initComponents();
        super.setLocationRelativeTo(null);
        
    }
    
    private void submenu_service(String set){
        if(set.equals("ADD")){
        service_sub1 = new JButton(sub1_txt1);
        service_sub1.setFont(setFont);
        service_sub1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        service_sub1.setBackground(Color.LIGHT_GRAY);
        service_sub1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png")));
        service_sub1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service_sub1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        
        service_sub2 = new JButton(sub1_txt2);
        service_sub2.setFont(setFont);
        service_sub2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        service_sub2.setBackground(Color.LIGHT_GRAY);
        service_sub2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png")));
        service_sub2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service_sub2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        
        service_sub3 = new JButton(sub1_txt3);
        service_sub3.setFont(setFont);
        service_sub3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        service_sub3.setBackground(Color.LIGHT_GRAY);
        service_sub3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png")));
        service_sub3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service_sub3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        
        panel1.add(service_sub1);
        panel1.add(service_sub2);
        panel1.add(service_sub3);
        }
        if(set.equals("REMOVE")){
            panel1.remove(service_sub1);
            panel1.remove(service_sub2);
            panel1.remove(service_sub3);
        }
        if(set.equals("NULL")){
            
        }
    }
    
    private void refreshFrame(){
        super.invalidate();
        super.validate();
        super.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panel_left = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        service = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        fuel = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        intake = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        ignition = new javax.swing.JButton();
        panel5 = new javax.swing.JPanel();
        engine = new javax.swing.JButton();
        panel6 = new javax.swing.JPanel();
        emission = new javax.swing.JButton();
        panel7 = new javax.swing.JPanel();
        control = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        idle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_menu.setBackground(Color.BLACK);
        panel_menu.setLayout(new javax.swing.BoxLayout(panel_menu, javax.swing.BoxLayout.PAGE_AXIS));

        panel1.setLayout(new java.awt.GridLayout(0, 1));

        service.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        service.setBackground(Color.ORANGE);
        service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        service.setText("Service adjustments");
        service.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        service.setPreferredSize(new java.awt.Dimension(157, 50));
        service.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        service.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                serviceItemStateChanged(evt);
            }
        });
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        panel1.add(service);

        panel_menu.add(panel1);

        panel2.setLayout(new java.awt.GridLayout(0, 1));

        fuel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        fuel.setText("Fuel system");
        fuel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fuel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fuel.setPreferredSize(new java.awt.Dimension(106, 50));
        fuel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        fuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelActionPerformed(evt);
            }
        });
        panel2.add(fuel);

        panel_menu.add(panel2);

        panel3.setLayout(new java.awt.GridLayout(0, 1));

        intake.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        intake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        intake.setText("Intake system");
        intake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intake.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        intake.setPreferredSize(new java.awt.Dimension(116, 50));
        intake.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel3.add(intake);

        panel_menu.add(panel3);

        panel4.setLayout(new java.awt.GridLayout(0, 1));

        ignition.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ignition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        ignition.setText("Ignition system");
        ignition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ignition.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ignition.setPreferredSize(new java.awt.Dimension(123, 50));
        ignition.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        ignition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignitionActionPerformed(evt);
            }
        });
        panel4.add(ignition);

        panel_menu.add(panel4);

        panel5.setLayout(new java.awt.GridLayout(0, 1));

        engine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        engine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        engine.setText("Engine sensors");
        engine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        engine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        engine.setPreferredSize(new java.awt.Dimension(128, 50));
        engine.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel5.add(engine);

        panel_menu.add(panel5);

        panel6.setLayout(new java.awt.GridLayout(0, 1));

        emission.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        emission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        emission.setText("Emission control system");
        emission.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emission.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emission.setPreferredSize(new java.awt.Dimension(181, 50));
        emission.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        emission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emissionActionPerformed(evt);
            }
        });
        panel6.add(emission);

        panel_menu.add(panel6);

        panel7.setLayout(new java.awt.GridLayout(0, 1));

        control.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emct/images/Services_48px.png"))); // NOI18N
        control.setText("Control system");
        control.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        control.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        control.setPreferredSize(new java.awt.Dimension(124, 50));
        control.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlActionPerformed(evt);
            }
        });
        panel7.add(control);

        panel_menu.add(panel7);

        javax.swing.GroupLayout panel_leftLayout = new javax.swing.GroupLayout(panel_left);
        panel_left.setLayout(panel_leftLayout);
        panel_leftLayout.setHorizontalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        panel_leftLayout.setVerticalGroup(
            panel_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panel_left);

        idle.setBackground(Color.LIGHT_GRAY);
        idle.setVisible(true);

        jLabel3.setForeground(setColor2);
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Idle speed");

        jLabel4.setForeground(setColor2);
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Adjustment - except Passat");

        jTable1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"All models", "770-870 rpm"}
            },
            new String [] {
                "Technical Data", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("• Idle speed electronically controlled.");

        jLabel2.setText("• No adjustment possible.");

        jLabel5.setText("• If idle speed not as specified: Check for air leaks in intake system. Carry out component and electrical tests.");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(setColor2);
        jLabel6.setText("Adjustment  -  Passat  -");

        jLabel7.setText("&");

        jButton1.setBackground(Color.ORANGE);
        jButton1.setText("FIG 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(Color.ORANGE);
        jButton2.setText("FIG 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("• Can only be adjusted using suitable diagnostic equipment.");

        jLabel9.setText("• Ensure ignition switched OFF.");

        jLabel10.setText("• Disconnect crankcase breather hose from pressure regulating valve.");

        jLabel11.setText("• Plug crankcase breather hose.");

        jLabel12.setText("• Start engine.");

        jLabel13.setText("• Initiate basic setting using suitable diagnostic equipment.");

        jLabel14.setText("• Allow to idle for 2 minutes.");

        jLabel15.setText("• Adjust idle speed with idle speed screw.");

        jTable3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"All models", "770-870 rpm"}
            },
            new String [] {
                "Technical Data", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton3.setBackground(Color.ORANGE);
        jButton3.setText("FIG 1");

        jButton4.setBackground(Color.ORANGE);
        jButton4.setText("FIG 2");

        javax.swing.GroupLayout idleLayout = new javax.swing.GroupLayout(idle);
        idle.setLayout(idleLayout);
        idleLayout.setHorizontalGroup(
            idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idleLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(idleLayout.createSequentialGroup()
                        .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(idleLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(idleLayout.createSequentialGroup()
                        .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(idleLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(idleLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jLabel10)
                    .addGroup(idleLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(idleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        idleLayout.setVerticalGroup(
            idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idleLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(60, 60, 60)
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scroll.setViewportView(idle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scroll)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        if(!service.isSelected()){
        service.setSelected(true);
        service.setBackground(setColor);
        submenu_service("ADD");
        refreshFrame();
        } else {
            service.setSelected(false);
        }
    }//GEN-LAST:event_serviceActionPerformed

    private void serviceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_serviceItemStateChanged
        if(evt.getStateChange()==ItemEvent.DESELECTED){
            submenu_service("REMOVE");
            refreshFrame();
            service.setBackground(Color.ORANGE);
        }
    }//GEN-LAST:event_serviceItemStateChanged

    private void emissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emissionActionPerformed

    private void controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelActionPerformed

    private void ignitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ignitionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(emct.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new emct().setVisible(true);
        });
    }

    private final Font setFont = new Font("Dialog", Font.BOLD, 11);
    private final Color setColor = new Color(255, 204, 0);
    private final Color setColor2 = new Color(15, 89, 193);
    private static JButton service_sub1;
    private static JButton service_sub2;
    private static JButton service_sub3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton control;
    private javax.swing.JButton emission;
    private javax.swing.JButton engine;
    private javax.swing.JButton fuel;
    private javax.swing.JPanel idle;
    private javax.swing.JButton ignition;
    private javax.swing.JButton intake;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton service;
    // End of variables declaration//GEN-END:variables
}
