/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emct.frames.b_fuel_system;

/**
 *
 * @author Catalin Glavan
 */
public class cold_start extends javax.swing.JPanel {

    /**
     * Creates new form cold_start
     */
    public cold_start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel114 = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jLabel138 = new javax.swing.JLabel();
        jButton46 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jLabel111 = new javax.swing.JLabel();
        jButton48 = new javax.swing.JButton();
        jLabel119 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jLabel113 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jLabel137 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton43 = new javax.swing.JButton();
        jLabel141 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jButton47 = new javax.swing.JButton();
        jLabel142 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jButton45 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();

        jLabel114.setText("• Ensure ignition switched OFF. ");

        jButton49.setBackground(java.awt.Color.orange);
        jButton49.setText("FIG 12");
        jButton49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton49.setFocusable(false);

        jLabel138.setText("• Disconnect engine coolant temperature (ECT) sensor multi-plug. ");

        jButton46.setBackground(java.awt.Color.orange);
        jButton46.setText("FIG 12");
        jButton46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton46.setFocusable(false);

        jScrollPane13.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Engine cranking", "Fuel spray for 1-4 secs."},
                {"Resistor between terminals", "3800 \u2126"}
            },
            new String [] {
                "Condition", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane13.setViewportView(jTable13);

        jLabel111.setText("• Do not disconnect multi-plug. Remove cold start injector. ");

        jButton48.setBackground(java.awt.Color.orange);
        jButton48.setText("FIG 14");
        jButton48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton48.setFocusable(false);

        jLabel119.setText("• Dry nozzle of cold start injector. ");

        jLabel118.setText("• Check for even conical spray.");

        jLabel110.setText("• Ensure ignition switched OFF. ");

        jLabel112.setText("• Position injector over suitable container ");

        jLabel120.setText("• Check that no drips of fuel leak from nozzle.");

        jLabel143.setText("• If LEO does not flash:Check wiring. ");

        jLabel117.setText("• Crank engine.");

        jLabel136.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(15, 89, 193));
        jLabel136.setText("Checking signal -");

        jLabel145.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(15, 89, 193));
        jLabel145.setText("&");

        jLabel144.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(15, 89, 193));
        jLabel144.setText("Checking operation -");

        jScrollPane12.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Engine cranking ", "Flashing for 1-4 secs. "},
                {"Resistor between terminals", "3800 \u2126"}
            },
            new String [] {
                "Condition", "LED"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane12.setViewportView(jTable12);

        jLabel113.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel113.setText("NOTE: Disconnect injector harness multi-plug before cranking tests,to prevent engine from starting. ");

        jButton32.setBackground(java.awt.Color.orange);
        jButton32.setText("FIG 12");
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setFocusable(false);

        jLabel137.setText("• Disconnect cold start injector multi-plug. ");

        jButton43.setBackground(java.awt.Color.orange);
        jButton43.setText("FIG 13");
        jButton43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton43.setFocusable(false);

        jLabel141.setText("• Briefly crank engine. ");

        jLabel140.setText("• Connect LEO test lamp between cold start injector harness multi-plug terminals ");

        jButton47.setBackground(java.awt.Color.orange);
        jButton47.setText("FIG 14");
        jButton47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton47.setFocusable(false);

        jLabel142.setText("• Check that LEO flashes.");

        jLabel116.setText("• Connect resistor between ECT sensor harness multi-plug terminals ");

        jLabel115.setText("• Disconnect engine coolant temperature (ECT) sensor multi-plug. ");

        jLabel109.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(15, 89, 193));
        jLabel109.setText("&");

        jLabel108.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(15, 89, 193));
        jLabel108.setText("Cold start injector");

        jLabel139.setText("• Connect resistor between ECT sensor harness multi-plug terminals ");

        jButton45.setBackground(java.awt.Color.orange);
        jButton45.setText("FIG 13");
        jButton45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton45.setFocusable(false);

        jButton44.setBackground(java.awt.Color.orange);
        jButton44.setText("FIG 12");
        jButton44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton44.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel108)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel136)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel109)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton43))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel137)
                                        .addComponent(jLabel114)
                                        .addComponent(jLabel138)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel139)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton44))
                                        .addComponent(jLabel141)
                                        .addComponent(jLabel142)
                                        .addComponent(jLabel143)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel140)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton45))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel144)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton46)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel145)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton47))
                                        .addComponent(jLabel113))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator7)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel110)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel112)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton48))
                                .addComponent(jLabel111)
                                .addComponent(jLabel117)
                                .addComponent(jLabel118)
                                .addComponent(jLabel119)
                                .addComponent(jLabel120)
                                .addComponent(jLabel115)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel116)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton49)))
                            .addGap(346, 346, 346)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel108)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel109)
                        .addComponent(jButton32)
                        .addComponent(jLabel136)
                        .addComponent(jButton43))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel113)
                    .addGap(26, 26, 26)
                    .addComponent(jLabel114)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel137)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel138)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel139)
                        .addComponent(jButton44))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel140)
                        .addComponent(jButton45))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel141)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel142)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel143)
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel144)
                        .addComponent(jButton46)
                        .addComponent(jLabel145)
                        .addComponent(jButton47))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel110)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel111)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel112)
                        .addComponent(jButton48))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel115)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel116)
                        .addComponent(jButton49))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel117)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel118)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel119)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel120)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    // End of variables declaration//GEN-END:variables
}
