/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emct.frames.b_fuel_system;

/**
 *
 * @author Catalin Glavan
 */
public class fuel_pump extends javax.swing.JPanel {

    /**
     * Creates new form fuel_pump
     */
    public fuel_pump() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel124 = new javax.swing.JLabel();
        jButton52 = new javax.swing.JButton();
        jLabel146 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel122 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jButton51 = new javax.swing.JButton();
        jLabel121 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jButton50 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jButton33 = new javax.swing.JButton();

        jLabel124.setText("• Switch ignition ON. ");

        jButton52.setBackground(java.awt.Color.orange);
        jButton52.setText("FIG 7");
        jButton52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton52.setFocusable(false);

        jLabel146.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(15, 89, 193));
        jLabel146.setText("Checking operation -");

        jLabel150.setText("• Connect battery voltage supply to relay base terminal 4 with switched lead");

        jLabel151.setText("• Fuel pump should run continuously when switch is operated.");

        jLabel134.setText("• Switch ignition ON. ");

        jLabel149.setText("• Remove fuel pump relay.");

        jLabel122.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(15, 89, 193));
        jLabel122.setText("&");

        jLabel147.setText("• Fuel pump should run for approximately 1 second. ");

        jLabel156.setText("• If battery voltage is not indicated: Check wiring.");

        jLabel148.setText("• If pump does not run:Switch ignition OFF. ");

        jButton51.setBackground(java.awt.Color.orange);
        jButton51.setText("FIG 15");
        jButton51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton51.setFocusable(false);

        jLabel121.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel121.setForeground(new java.awt.Color(15, 89, 193));
        jLabel121.setText("Fuel pump ");

        jLabel152.setText("• If pump does not run:Switch ignition OFF.");

        jLabel153.setText("• Disconnect fuel pump multi-plug.");

        jLabel135.setText("• Check for battery voltage between harness multi-plug terminals");

        jButton50.setBackground(java.awt.Color.orange);
        jButton50.setText("FIG 15");
        jButton50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton50.setFocusable(false);

        jScrollPane14.setBorder(javax.swing.BorderFactory.createTitledBorder("Technical Data"));

        jTable14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1 & 4", "Battery voltage"}
            },
            new String [] {
                "Terminals", "Voltage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane14.setViewportView(jTable14);

        jButton33.setBackground(java.awt.Color.orange);
        jButton33.setText("FIG 7");
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel147)
                            .addComponent(jLabel124)
                            .addComponent(jLabel148)
                            .addComponent(jLabel149)
                            .addComponent(jLabel151)
                            .addComponent(jLabel152)
                            .addComponent(jLabel153)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel150)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton52))
                            .addComponent(jLabel134)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel135)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton51))
                            .addComponent(jLabel156)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel121)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel146)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel122)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton50)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel121)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel122)
                    .addComponent(jButton33)
                    .addComponent(jLabel146)
                    .addComponent(jButton50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel124)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel147)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel148)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel149)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel150)
                    .addComponent(jButton52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel151)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel152)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel153)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel134)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel135)
                    .addComponent(jButton51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel156)
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable14;
    // End of variables declaration//GEN-END:variables
}
